
##############################
## for testing 
##
## NB: use rake -I ./lib dev:test      # fresh import (starts w/ clean wipe out)

namespace :worlddb do
  
  BUILD_DIR = "./build"
  
  WORLD_DB_PATH = "#{BUILD_DIR}/world.db"

  DB_CONFIG = {
    :adapter   =>  'sqlite3',
    :database  =>  WORLD_DB_PATH
  }

  directory BUILD_DIR

  task :clean do
    rm WORLD_DB_PATH if File.exists?( WORLD_DB_PATH )
  end

  task :env => BUILD_DIR do
    require 'worlddb'   ### NB: for local testing use rake -I ./lib dev:test e.g. do NOT forget to add -I ./lib
    require 'logutils/db'

    LogUtils::Logger.root.level = :info

    pp DB_CONFIG
    ActiveRecord::Base.establish_connection( DB_CONFIG )
  end

  task :create => :env do
    LogDb.create
    WorldDb.create
  end
  
  task :import => :env do
    WorldDb.read_setup( 'setups/europe.at', '../world.db', skip_tags: true )  # populate world tables
    WorldDb.stats
  end


  desc 'worlddb - build from scratch'
  task :build => [:clean, :create, :import]

  desc 'worlddb - update'
  task :update => [:import]

end  # namespace :worlddb
